### ISSUE TITLE
Redundant sum?

### ISSUE THREAD

**Issue by romanbsd** [sigsep/norbert#27]
Was it supposed to be `v_g` instead of `v`? Otherwise the sum is operation is redundant.

https://github.com/sigsep/norbert/blob/master/norbert/contrib.py#L73

**Comment by aliutkus** [comment]
ups, yes, of course. This was actually fixed in some other branches but not in the `master`
fixed in dac53ed72556e864849397e6a2e43cc6861ccaae
thanks for pointing that out and sorry for the inconvenience

**Comment by faroit** [comment]
@aliutkus is there something that needs to be merged?

**Comment by aliutkus** [comment]
Well, actually there is some things we could do about ram usage, yes, especially in the `ramusage` branch, but I need to investigate what exactly is in `residual` and not in `ramusage` and also check whether `ramusage` is not too slow.

Let's say that fixing this issue was quick, but I need a little bit more time to clean up stuff regarding the open branches
